language: en

pipeline:
- name: WhitespaceTokenizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
  epochs: 100
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
- name: FallbackClassifier
  threshold: 0.3    # Confidence threshold for fallback

policies:
- name: RulePolicy
  core_fallback_action_name: "action_default_fallback"
  core_fallback_threshold: 0.3
  enable_fallback_prediction: true
assistant_id: 20241118-020212-natural-formula
