# -*- coding: utf-8 -*-
"""Pycaret_AutoML_Diabetes_all.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ltZJGt0Obe4RaoFxRu1NUlLTjxDNRHMk
"""

pip install pycaret

import pandas as pd
from pycaret.classification import setup, compare_models, tune_model, pull

# Load the dataset
file_path = "diabetes_normal_data.csv"  # Path to your dataset
data = pd.read_csv(file_path)

# Define target variable
target_column = 'diabetes'  # Replace 'diabetes' with the name of your target column

import random

random_seed = 42

clf_setup = setup(data=data, target=target_column, session_id=random_seed, log_experiment=False, verbose=False)

# Compare models and select the top 5
best_models = compare_models(n_select=5)

# Optimize hyperparameters for the top 5 models
tuned_models = [tune_model(model) for model in best_models]

# Print the performance metrics of the tuned models
print("\nTop 5 Models with Optimized Hyperparameters:\n")
for i, tuned_model in enumerate(tuned_models, start=1):
    print(f"Model {i}: {tuned_model}")
    print(pull())  # Display the performance metrics for the tuned model
    print("\n" + "="*50 + "\n")